<a href="https://colab.research.google.com/github/ajeet7iitm/MLT_OPPE/blob/main/sitaram_vector_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'''|| SITARAM ||
|| JAI MATA DI ||
|| SHREE GURUVE NAMAH ||
|| OM NAMAH PARVATI PATYE HAR HAR MAHADEV ||
SITARAM RADHE RADHE MAHADEV'''

'|| SITARAM ||\n|| JAI MATA DI ||\n|| SHREE GURUVE NAMAH ||\n|| OM NAMAH PARVATI PATYE HAR HAR MAHADEV ||\nSITARAM RADHE RADHE MAHADEV'

In [29]:
import numpy as np

In [6]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=x+y
z

array([5, 7, 9])

In [9]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=x*y
z

array([ 4, 10, 18])

In [10]:
x=np.array([1,2,3])
y=3*x
y

array([3, 6, 9])

In [11]:
x=np.array([1,2,3,4])
x**2

array([ 1,  4,  9, 16])

In [12]:
x=np.array([1,10,100,1000,10_000,100_000])
y=np.log10(x)
y

array([0., 1., 2., 3., 4., 5.])

In [14]:
np.log2(x)

array([ 0.        ,  3.32192809,  6.64385619,  9.96578428, 13.28771238,
       16.60964047])

In [15]:
y.dtype

dtype('float64')

In [16]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [17]:
x=np.array([1,np.e,np.e**2,np.e**3])
np.log(x)

array([0., 1., 2., 3.])

In [18]:
x=np.array([1,2,3])
c=5
x+c

array([6, 7, 8])

In [19]:
x=np.array([-1,0,1,2])
5*x-2

array([-7, -2,  3,  8])

In [20]:
x=np.array([1,2,3,4])
y=np.array([-4,-5,-6,-7])
np.dot(x,y)

-60

In [21]:
x@y

-60

In [22]:
w=np.zeros(5)
w

array([0., 0., 0., 0., 0.])

In [23]:
ones=np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [24]:
fives=np.ones(5)*5
fives

array([5., 5., 5., 5., 5.])

In [25]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [31]:
x=np.array([1,2,3])
print(np.linalg.norm(x,ord=2)) #ridge
print(np.linalg.norm(x, ord=1)) #lasso

3.7416573867739413
6.0


In [32]:
x=np.array([1,2,3,4])
print(x.shape)
print(x.ndim)

(4,)
1
